config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:index, :show] do 
    resources :skills
  end
  resources :projects do
    resources :roles, only: [:index, :new, :create] do 
      resources :skills
    end
    resources :skills
  end
  get "/pages/*id" => 'pages#show', as: :page, format: false
  root to: 'pages#show', id: 'home'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :users, through: :roles
  has_many :roles 
  has_many :skills, as: :skilled

  
  validates :name, presence: true,
                   uniqueness: true

  accepts_nested_attributes_for :skills, allow_destroy: true
  accepts_nested_attributes_for :roles, allow_destroy: true

  mount_uploader :image, ImageUploader

end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  has_many :skills, as: :skilled

end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :skilled, polymorphic: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :signin
  has_many :projects, :through => :roles
  has_many :roles
  has_many :skills, as: :skilled

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if signin = conditions.delete(:signin)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => signin.downcase }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    projects_path    
  end
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:signin) }
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :username, :password, :password_confirmation) }
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include HighVoltage::StaticPage


  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_project, except: [:index, :new, :create]

  def index
    @projects = Project.all
  end

  def show
    @users = @project.users
  end

  def new
    @project = Project.new    
    @project.skills.build

  end

  def edit    
  end

  def create
    @project = Project.new(project_params)
    @project.owner = current_user.username
    

    if @project.save
      flash[:notice] = "Your project has been successfully created."
      redirect_to projects_path
    else
      flash[:alert] = "Your project could not be created."
      render 'new'
    end
  end

  def update    
  end

  def destroy    
  end

    private

      def set_project
        @project = Project.find(params[:id])
      end

      def project_params
        params.require(:project).permit(:name, :body, :owner, skills_attributes: [ :id, :skill_content ], roles_attributes: [:id, :project_id])
      end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController

  before_action :authenticate_user!, only: [:create, :update, :destroy]

  def index
    @project = Project.find(params[:project_id])
    @user = current_user
    @roles = Role.where(["project_id = ? AND user_id = ?", @project.id, @user.id] )
   
  end

  def new
    @project = Project.find(params[:project_id])
    @role = Role.new
  end

  def create
    @role = Role.new(role_params)
    @project = Project.find(params[:project_id])
    @user = current_user
    
    if @role.save 
      @user.roles << @role
    # A FAIRE @role.skills << params[????]
      @project.roles << @role
      flash[:notice] = "You successfully followed this project."
      redirect_to @project
    else
      render 'new'
      flash[:alert] = "You couldn't follow this project."
    end
  end

  private
    def role_params
      params.require(:role).permit(:motivation, :user_id, :project_id)
    end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :load_skilled

  def index
    @skills = @skilled.skills
  end

  def show
    @skill = @skilled.find(params[:id])
  end

  def new
    @skill = @skilled.skills.build
    render partial: "skills/form",
           locals: { number: params[:number].to_i,
                     skill: @skill }

  end

  def create
    @skill = @skilled.skills.new(skill_params)

    if @skill.save
      flash[:notice] = "Skill created"
      redirect_to [@skill, :skills]
    else
      render :new
    end
  end

  def edit
    @skill = @skilled.find(params[:id])

  end

  def update
    @skilled.skills.update_attribute(skill_params)
    flash[:notice] = "Skill updated"
  end

  def destroy
    @skilled.skills.destroy

  end

  private
    def skill_params
      params.require(:skill).permit(:skill_content)
    end
    def load_skilled
      klass = [Role, User, Project].detect { |c| params["#{c.name.underscore}_id"] }
      @skilled = klass.find(params["#{klass.name.underscore}_id"])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_footer.html.erb
  <ul>
    <li><%= link_to 'About', page_path('about') %> </li>
    <li>test </li>
    <li>test </li>
    <li>test </li>
  </ul>

app/views/layouts/_navbar.html.erb
<div class="sticky">
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Home", root_path %></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active"><a href="#">Right Button Active</a></li>
      <li class="has-dropdown">
        <% if current_user %>
        <a href="#">Logged in as <%= current_user.username %></a>
        <% else %>
        <a href="#">Log in</a>
        <% end %>
        
        <ul class="dropdown">
        <% if current_user %>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete, data: {confirm: "Are you sure?"} %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <li class="active"><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
        </ul>

      </li>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      <li><%= link_to "See Projects", projects_path %></li>
    </ul>
  </section>
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Adopt a Noob!" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
<div class="navbar">
  <%= render 'layouts/navbar' %>
</div>
<div class="notalertph">
  <% if notice || alert %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <% end %>
</div>

<div class="page-layout">
    <%= yield %>
</div>

<div id='footer'>
<%= render 'layouts/footer' %>
</div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/pages/about.html.erb
<h2>This is the About Page</h2>


<p>This website is for fun!</p>

 

app/views/pages/home.html.erb
<h2>This is the HomePage YeaH!</h2>
<% if signed_in?  %>
<%= current_user.username %>
<% end %>

<p>Homepage gotta be root of website instead of signin form from Devise</p>

app/views/projects/_form.html.erb
<%= form_for @project, :html => {:multipart => true} do |f| %>
  <%= f.label :name %><br />
  <%= f.text_field :name %>

  <%= f.label :body, "Description" %><br />
  <%= f.text_area :body %><br /> 

<% number = 0 %>
<div id="skills">
 <%= render partial: "skills/form",
            locals: {number: number} %>

<%= link_to_add_fields "Add another skill", f, :skills %>
</div>
<div class="image">
 <%=  f.file_field :image %>
</div>

  <%= f.submit %>


<% end %>

app/views/projects/_skill_fields.html.erb
  <%= f.label :skill_content, "skill" %><br />
  <%= f.text_area :skill_content %><br />

app/views/projects/index.html.erb
<%= link_to "New Project", new_project_path %>
<% @projects.each do |project| %>
<div class="container">
  <h3><%= link_to project.name, project_path(project) %></h3>created by <%= project.owner %><br />
  <%= project.body %><br />
    
    participants: 
      <ul>
      <li><%= project.owner %> (Owner)</li>
      <% project.users.each do |user| %>
      <li><%= user.username %></li>
      <% end %>
      </ul>
        <ul>
        <% project.skills.each do |skill| %>
        
      <li>Skill: <%= skill.skill_content %>, with ID: <%= skill.id %> </li>
       <% end %>
      </ul>

  </div>
<% end %>

app/views/projects/new.html.erb
<h4>Create your own project</h4>

<%= render 'form' %>

app/views/projects/show.html.erb
<%= @project.name %> <%= link_to "Follow Project", new_project_role_path(@project) %><br />
Created by <%= @project.owner %><br />
<%= @project.body %><br />
<% @users.each do |user| %>
  <%= user.username %><br />
<% end %>
Select the skills you have from the project's skills.<br />
<%= collection_check_boxes(@project, :skill_ids, @project.skills, :id, :skill_content) %>
<%= submit_tag 'Follow' %>

app/views/roles/index.html.erb
<% @roles.each do |role| %>
  <% role.skills.each do |skill| %>
    <%= skill.skill_content %>
  <% end %>
<% end %>

app/views/roles/new.html.erb
To follow a project, please tell us:<br /> 

Pistes de développement :
  imaginer un modèle mentor et un modèle apprentis

  mentor belongs_to role
  mentor has_many skills
  apprentis has_many skills
  apprentis belongs_to role

  mentor has_many :skills
  apprentis has_many :skills
  
  role has_many :skills through mentor
  role has_many :skills through apprentis


  solution au cas où un user veut s'inscrire en mentor sur un skill et apprentis sur un autre skill pour le meme projet.




  <%= form_for [@project, @role] do |f| -%>
  <%= f.label "Your motivation" %>
  <%= f.text_area :motivation %>
  Select the skills you have from the project's skills.<br />
<%= collection_check_boxes(@project, :skill_ids, @project.skills, :id, :skill_content) %>
  <%= f.submit "Enroll!" %>
    
  <% end -%>

app/views/skills/_form.html.erb
 <%= fields_for @project do |f| %>
 <%= f.fields_for :skills, child_index: number do |f_skill| %><br />
  <%= f_skill.label :skill_content, "#{number += 1}" %><br />
  <%= f_skill.text_field :skill_content  %>
  <% end %>
  <% end %>

app/views/skills/create.html.erb
<h1>Skills#create</h1>
<p>Find me in app/views/skills/create.html.erb</p>

app/views/skills/destroy.html.erb
<h1>Skills#destroy</h1>
<p>Find me in app/views/skills/destroy.html.erb</p>

app/views/skills/edit.html.erb
<h1>Skills#edit</h1>
<p>Find me in app/views/skills/edit.html.erb</p>

app/views/skills/index.html.erb
<% @skills.each do |skill| %>
  <%= skill.skill_content %>
<% end %>

app/views/skills/new.html.erb
<h1>Skills#new</h1>
<p>Find me in app/views/skills/new.html.erb</p>

app/views/skills/show.html.erb
<h1>Skills#show</h1>
<p>Find me in app/views/skills/show.html.erb</p>

app/views/skills/update.html.erb
<h1>Skills#update</h1>
<p>Find me in app/views/skills/update.html.erb</p>

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.username, user_path(user) %></li>
    <li>skills désirés</li>
    <li><%= user.email %></li>
    <% user.projects.each do |project| %>
    <%= project.name %><br /><br />
    <% end %>
  <% end %>
</ul>

app/views/users/show.html.erb
<h3><%= @user.username %>'s profile</h3>

<% @user.roles.each do |role| %>
<% unless role.motivation.blank?  %>
  Motivation: <%= role.motivation %><br />
<% end %>
<% end %>

Mes skills:
<% @user.skills.each do |skill| %>
 <ul> 
 <li><%= skill.skill_content %></li>
 </ul>
<% end  %>